# docker-compose.yml

version: '3.8'
services:
  nest:
    build:
        context: .
        dockerfile: Dockerfile
<<<<<<< HEAD
    image: nest/mlv:v1
=======
    image: nest/mlv
>>>>>>> 751bc1a (feat(build) : add docker-compose.yml , add prisma and generate project)
    restart: always
    ports:
      - '3000:3000'
    networks:
      - postgres-network
    environment:
      - DATABASE_URL=postgres://root:strong@postgres:5432/mlv
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=strong
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres-network

volumes:
  postgres:

networks:
  postgres-network:
    driver: bridge